/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package test.compiler

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class CompilerTest {

    @Test
    fun `should work with local functions`() {
        // This doesn't work with plugin
//        val property = Property("Hello")
//        assertEquals(property.get(), "Different hello")
    }

    @Test
    fun `should work with assign on object`() {
        val javaCompile = JavaCompile()
        javaCompile.sourceCompatibility = "1.8"
        javaCompile.targetCompatibility = "1.8"
        assertEquals(javaCompile.sourceCompatibility, Property("1.8"))
        assertEquals(javaCompile.targetCompatibility, Property("1.8"))

        javaCompile.sourceCompatibility = Property("11")
        javaCompile.targetCompatibility = Property("11")
        assertEquals(javaCompile.sourceCompatibility, Property("11"))
        assertEquals(javaCompile.targetCompatibility, Property("11"))
    }

    @Test
    fun `should work with apply on object`() {
        val javaCompile = JavaCompile()
        javaCompile.apply {
            sourceCompatibility = "1.8"
            targetCompatibility = "1.8"
        }
        assertEquals(javaCompile.sourceCompatibility, Property("1.8"))
        assertEquals(javaCompile.targetCompatibility, Property("1.8"))

        javaCompile.apply {
            sourceCompatibility = Property("11")
            targetCompatibility = Property("11")
        }
        assertEquals(javaCompile.sourceCompatibility, Property("11"))
        assertEquals(javaCompile.targetCompatibility, Property("11"))
    }
}
