/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
@file:Suppress("UnusedImport")

package test.compiler

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals
import test.compiler.CompileTask
import test.compiler.Property
import test.compiler.assign

class CompilerTest {

    @Test
    fun `should work with local functions`() {
        val property = Property("Hello")
        property = "Different hello"
        assertEquals(property.get(), "Different hello")
    }

    @Test
    fun `should work with assign on object`() {
        val compileTask = CompileTask()
        compileTask.sourceCompatibility = "1.8"
        compileTask.targetCompatibility = "1.8"
        assertEquals(compileTask.sourceCompatibility, Property("1.8"))
        assertEquals(compileTask.targetCompatibility, Property("1.8"))

        compileTask.sourceCompatibility = Property("11")
        compileTask.targetCompatibility = Property("11")
        assertEquals(compileTask.sourceCompatibility, Property("11"))
        assertEquals(compileTask.targetCompatibility, Property("11"))
    }

    @Test
    fun `should work with apply on object`() {
        val compileTask = CompileTask()
        compileTask.apply {
            sourceCompatibility = "1.8"
            targetCompatibility = "1.8"
        }
        assertEquals(compileTask.sourceCompatibility, Property("1.8"))
        assertEquals(compileTask.targetCompatibility, Property("1.8"))

        compileTask.apply {
            sourceCompatibility = Property("11")
            targetCompatibility = Property("11")
        }
        assertEquals(compileTask.sourceCompatibility, Property("11"))
        assertEquals(compileTask.targetCompatibility, Property("11"))
    }
}
